/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Logica.*;
/**
 *
 * @author Cristopher Matus
 */
public class Mundial extends javax.swing.JFrame {
 
    


    /**
     * Creates new form Mundial
     */
    public Mundial() {
        initComponents();
        cargarDatos();
        ingresarDatos();
        setLocationRelativeTo(null);
        setResizable(false);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        tbpCAF = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCAF = new javax.swing.JTable();
        btnSimularCAF = new javax.swing.JButton();
        btnSimularTodoCAF = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtSimuladosCAF = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConcacaf = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCONMEBOL = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblUEFA = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblOFC = new javax.swing.JTable();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblClasificados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbpCAF.setBackground(new java.awt.Color(153, 153, 255));
        tbpCAF.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );

        tbpCAF.addTab("", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        tblCAF.setBackground(new java.awt.Color(102, 102, 102));
        tblCAF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblCAF.setForeground(new java.awt.Color(255, 255, 255));
        tblCAF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pos", "Seleccion", "PTS", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"
            }
        ));
        jScrollPane1.setViewportView(tblCAF);

        btnSimularCAF.setText("Simular");
        btnSimularCAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularCAFActionPerformed(evt);
            }
        });

        btnSimularTodoCAF.setText("Simular Todo");

        txtSimuladosCAF.setColumns(20);
        txtSimuladosCAF.setRows(5);
        jScrollPane7.setViewportView(txtSimuladosCAF);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimularTodoCAF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimularCAF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnSimularCAF)
                        .addGap(46, 46, 46)
                        .addComponent(btnSimularTodoCAF))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 57, Short.MAX_VALUE))
        );

        tbpCAF.addTab("CAF", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        tblConcacaf.setBackground(new java.awt.Color(255, 255, 153));
        tblConcacaf.setBorder(new javax.swing.border.MatteBorder(null));
        tblConcacaf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pos", "Seleccion", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"
            }
        ));
        jScrollPane2.setViewportView(tblConcacaf);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 432, Short.MAX_VALUE))
        );

        tbpCAF.addTab("Concacaf", jPanel3);

        tblCONMEBOL.setBackground(new java.awt.Color(0, 102, 153));
        tblCONMEBOL.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tblCONMEBOL.setForeground(new java.awt.Color(255, 255, 153));
        tblCONMEBOL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pos", "Selección", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Title 10"
            }
        ));
        jScrollPane3.setViewportView(tblCONMEBOL);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        tbpCAF.addTab("CONMEBOL", jPanel4);

        jTabbedPane3.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane3.setForeground(new java.awt.Color(0, 204, 204));

        tblUEFA.setBackground(new java.awt.Color(51, 51, 51));
        tblUEFA.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tblUEFA.setForeground(new java.awt.Color(255, 255, 255));
        tblUEFA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pos", "Selección", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Title 10"
            }
        ));
        jScrollPane5.setViewportView(tblUEFA);

        jTabbedPane3.addTab("Europa", jScrollPane5);

        tbpCAF.addTab("UEFA", jTabbedPane3);

        jTabbedPane2.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTabbedPane2.setForeground(new java.awt.Color(102, 255, 102));

        tblOFC.setBackground(new java.awt.Color(204, 102, 0));
        tblOFC.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tblOFC.setForeground(new java.awt.Color(51, 204, 255));
        tblOFC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pos", "Selección", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Title 10"
            }
        ));
        jScrollPane4.setViewportView(tblOFC);

        jTabbedPane2.addTab("Oceanía", jScrollPane4);

        tbpCAF.addTab("OFC", jTabbedPane2);

        tblClasificados.setBackground(new java.awt.Color(0, 102, 102));
        tblClasificados.setForeground(new java.awt.Color(204, 204, 204));
        tblClasificados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pos", "Selección", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"
            }
        ));
        jScrollPane6.setViewportView(tblClasificados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addGap(93, 93, 93))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 319, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Clasificados", jPanel5);

        tbpCAF.addTab("Clasificados", jTabbedPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpCAF)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpCAF)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//explicar aqui y no todo
    public void cargarDatos() {
        //creo el modelo
        DefaultTableModel modelo = new DefaultTableModel(new Object[]
        {"Pos", "Selección", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"}, 0);
        //uso ese mismo modelo para las tablas que se van a usar
        this.tblCAF.setModel(modelo);
        this.tblConcacaf.setModel(modelo);
        this.tblCONMEBOL.setModel(modelo);
        this.tblUEFA.setModel(modelo);
        this.tblOFC.setModel(modelo);
        this.tblClasificados.setModel(modelo);
        //creo un objeto para poner lo de los puntos en 0
        Object[] datos = 
        //este es complicado entonces van notas
        //modelo es la instancia
        //DataVector es un metodo que pone los datos usando un vector de vectores y uno de objetos
        modelo.setDataVector
        //este establece los datos que guardamos en el objeto "datos"(vector de vectores tiene los datos)        
        (new Object[][]{datos, datos, datos, datos, datos, datos},
                //y este tiene el nombre de las columnas de la tabla en la que vamos a
                // meter los datos(vector de objetos tiene las columnas)
                new Object[]
        {"Pos", "Selección", "Pts", "PJ", "PG", "PE", "PP", "GF", "GC", "Dif"});

    }
   public void ingresarDatos() {
    
}
    
    private void btnSimularCAFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularCAFActionPerformed
      
    }//GEN-LAST:event_btnSimularCAFActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimularCAF;
    private javax.swing.JButton btnSimularTodoCAF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable tblCAF;
    private javax.swing.JTable tblCONMEBOL;
    private javax.swing.JTable tblClasificados;
    private javax.swing.JTable tblConcacaf;
    private javax.swing.JTable tblOFC;
    private javax.swing.JTable tblUEFA;
    private javax.swing.JTabbedPane tbpCAF;
    private javax.swing.JTextArea txtSimuladosCAF;
    // End of variables declaration//GEN-END:variables
}
